frr version 8.0
frr defaults traditional
hostname router2
log syslog informational
no ipv6 forwarding

interface eth1
 description WAN-LINK-1-PRIMARY
 ip address 10.0.0.2/30
!
interface eth2
 description WAN-LINK-2-BACKUP
 ip address 10.0.1.2/30
!

! Static route back to Router1 LAN
ip route 192.168.1.0/24 10.0.0.1 10
ip route 192.168.1.0/24 10.0.1.1 20

line vty
!